railsapp/config/routes.rb
Webapp::Application.routes.draw do
  get "home/add_course"
  get "home/courses"
  match "/home/remove_course" => "home#remove_course"
  resources :home
  
  resources :courses do 
    resources :assignments
    resources :announcements
  end
    
  resources :grades
  
  devise_for :users
    
   
  
  

  root :to => 'home#index'

end

railsapp/app/models/announcement.rb
class Announcement < ActiveRecord::Base
  belongs_to :course
end

railsapp/app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  
  def show
    @course = Course.find(params[:course_id])
    @announcement = @course.announcements.find(params[:id])
  end

  def create
    @course = Course.find(params[:course_id])
    @announcement = @course.announcements.create(params[:announcement])
    
    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @course, notice: "Announcement created successfully." }
        format.json { render json: @announcement, status: :created, location: @announcement}      
      else 
        format.html { render action :"new"}
        format.json { render json: @announcement.errors, status: :unprocessable_entity}
      end
    end
    
  end
  
  def new
    @announcement = Announcement.new
    @course = Course.find(params[:course_id])
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announcement }
    end
  end

  def edit
    @course = Course.find(params[:course_id])
    @announcement = Announcement.find(params[:id])
  end
  def update
    @course = Course.find(params[:course_id])
    @announcement = Announcement.find(params[:id])
    
    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to(course_announcement_path(@announcement.course, @announcement), notice: "Announcement editted successfully.") }
      else
        format.html { render action :"edit"}
      end
    end
  end
  
end

railsapp/app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

railsapp/app/views/announcements/_form.html.erb
<%= form_for [@course, @announcement] do |f|%>
	<div class="field">
		<%= f.label :title%><br />
		<%= f.text_field :title%>
	</div>
	<div class="field">
		<%= f.label :text%><br />
		<%= f.text_area :text, :rows => 3 %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>

<%end%>

railsapp/app/views/announcements/_form.mobile.erb
<%= form_for [@course, @announcement] do |f|%>
	<div class="field">
		<%= f.label :title%><br />
		<%= f.text_field :title%>
	</div>
	<div class="field">
		<%= f.label :text%><br />
		<%= f.text_area :text, :rows => 3 %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>

<%end%>

railsapp/app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Back',  course_announcement_path(@announcement.course,@announcement) %>

railsapp/app/views/announcements/edit.mobile.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', course_announcement_path(@announcement.course, @announcement) %>

railsapp/app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<br/>
<%= link_to 'Back', courses_path %>

railsapp/app/views/announcements/new.mobile.erb
<h1>New announcement</h1>

<%= render 'form' %>

<br/>
<%= link_to 'Back', courses_path %>

railsapp/app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>
	
<p>
	<%= @announcement.updated_at.strftime("%A, %b %d - %I:%M %p") %>
	<h1><%= @announcement.title%></h1>
</p>

<p>
  	<div class="announcement"><b><%= @announcement.text %></b></div>
</p>

<% if can? :update, Announcement%>
	<% if @announcement.course.professor == current_user %>
		<%= link_to "Edit Announcement", edit_course_announcement_path(@announcement.course, @announcement)%>
		<%= link_to "Back", course_path(@announcement.course)%>

	<% end %>
<%end%>

railsapp/app/views/announcements/show.mobile.erb
<p id="notice"><%= notice %></p>
	
<p>
	<%= @announcement.updated_at.strftime("%A, %b %d - %I:%M %p") %>
	<h1><%= @announcement.title%></h1>
</p>

<p>
  	<div class="announcement"><b><%= @announcement.text %></b></div>
</p>

<% if can? :update, Announcement%>
	<% if @announcement.course.professor == current_user %>
		<%= link_to "Edit Announcement", edit_course_announcement_path(@announcement.course, @announcement)%>
	<% end %>
<%end%>