railsapp/config/routes.rb
Webapp::Application.routes.draw do
  get "home/add_course"
  get "home/courses"
  match "/home/remove_course" => "home#remove_course"
  resources :home
  
  resources :courses do 
    resources :assignments
    resources :announcements
  end
    
  resources :grades
  
  devise_for :users
    
   
  
  

  root :to => 'home#index'

end

railsapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    
    @mycourses = Course.all
    @show_dialog = (cookies[:last_seen_dialog] == nil || Time.now.to_f - cookies[:last_seen_dialog].to_f > 1800)

    respond_to do |format|
      
      format.html # index.html.erb
      format.json { render :json => { :var1 => @mycourses } }
    end
    
    session[:has_seen_dialog] = true;
    cookies[:last_seen_dialog] = Time.now.to_f

  end

  def courses
    @courses = current_user.courses
  end
  
  def add_course
    
  end
  
  def create
    @user = current_user
    
    course_ids = params[:courses]
    unless course_ids.blank?
      course_ids.each do |course_id|
        course = Course.find(course_id)
        if @user.enrolled?(course) == false then
          @user.courses << course
        end
        
      end
    end
    redirect_to "/home/courses"
  end
  
  def remove_course
    @user = current_user
    
    course_ids = params[:courses]
    
    unless course_ids.blank?
      course_ids.each do |course_id|
        course = Course.find(course_id)
        if @user.enrolled?(course)
          @user.courses.delete(course)
        end
        
      end
    end    

  end
  
  def remove_courses
    
    for course in current_user.courses do
      current_user.courses.delete(course)
    end
    
    redirect_to "/home/courses"
  end
end

railsapp/app/helpers/home_helper.rb
module HomeHelper
end

railsapp/app/views/home/_form.html.erb
<%= form_tag("/home") do |f|%>	
	<table>
	  <tr>
	    <th>Course</th>
	    <th>Enroll</th>	    
	  </tr>
	
	<% current_user.unenrolled_courses.each do |c| %>	
		<tr>
			<td><%= c.course_name %></ts>
		    <td><%= radio_button_tag(:course_id, c.id)%>
			</td>	
		</tr>
	<% end %>
	</table>
	<%= submit_tag("Register")%>
<% end %>

railsapp/app/views/home/_form.mobile.erb
<%= form_tag("/home") do |f|%>	
	<table>
	  <tr>
	    <th>Course</th>
	    <th>Enroll</th>	    
	  </tr>
	
	<% current_user.unenrolled_courses.each do |c| %>	
		<tr>
			<td><%= c.course_name %></ts>
		    <td><%= radio_button_tag(:course_id, c.id)%>
			</td>	
		</tr>
	<% end %>
	</table>
	<%= submit_tag("Register")%>
<% end %>

railsapp/app/views/home/add_course.html.erb
<h1>Available courses for <%= current_user.username %></h1>
<%= render :file => '/home/add_course_form' %>
<br />
<br />
<br />
<%= link_to 'Back', home_courses_path %>

railsapp/app/views/home/add_course.mobile.erb
<h1>Available courses for <%= current_user.username %></h1>
<%= render :file => '/home/add_course_form' %>
<br />
<br />
<br />
<%= link_to 'Back', home_courses_path %>

railsapp/app/views/home/add_course_form.html.erb
	<%= form_tag("/home") do |f|%>	
		<table>
		  <tr>
		    <th>Course</th>
		    <th>Enroll</th>	    
		  </tr>
		
		<% current_user.unenrolled_courses.each do |c| %>	
			<tr>
				<td><%= c.course_name %></ts>
			    <td><%= check_box_tag("courses[]", c.id)%>
				</td>	
			</tr>
		<% end %>
		</table>
		<%= submit_tag("Register")%>
	<% end %>

railsapp/app/views/home/add_course_form.mobile.erb
	<%= form_tag("/home") do |f|%>	
		<table>
		  <tr>
		    <th>Course</th>
		    <th>Enroll</th>	    
		  </tr>
		
		<% current_user.unenrolled_courses.each do |c| %>	
			<tr>
				<td><%= c.course_name %></ts>
			    <td><%= check_box_tag("courses[]", c.id)%>
				</td>	
			</tr>
		<% end %>
		</table>
		<%= submit_tag("Register")%>
	<% end %>

railsapp/app/views/home/courses.html.erb
<% if current_user != nil && !current_user.has_seen_courses %>
	<script>
	$(document).ready(function(){
		setTimeout(function(){
			$("div.help a.modalInput").trigger('click');
		}, 100);
	});
	</script>
	<% current_user.has_seen_courses = true %>
	<% current_user.save %>
<% end %>


<div class="modal" id="yesno">
  <h2>Courses</h2>

  <p>
  	Here you can see a list of every course you are <% if current_user.role == "teacher"%> teaching. <% else %> enrolled in. <% end %>
    <br/>
    <br/>
    Notice the links below the list of courses.  From these you can manage your curriculum online:
    <ul>
	    <% if current_user.role == "teacher" %>
	    <% else %>
	    	<li><b>Add a course</b> - Here you can check off from a list of available courses, the ones you would like to enroll in.</li>
	    	<li><b>Remove a course</b> - Here you can drop a course or more, if you've found that they no longer interest you.</li>
	    <% end %>
    </ul>
  </p>

  <p>
    <button class="close"> Ok </button><span class="note"> You can also hit escape to close this dialog. </span>
  </p>
</div>

<p id="notice"><%= notice %></p>

<p>
	<h1>My courses:</h1>
	<br/>
	<table class = "list" cellspacing="15">
		<thead>
			<tr>
				<th>Course</th>
				<th>Description</th>
			</tr>
		</thead>
		<tbody>
			<% for course in current_user.courses do %>
			
				<tr>
					<td class = "middle"><%= link_to course.course_name, course %></td>
					<td class = "middle"><%= course.course_description%></td>
				</tr>
			<%end%>
		</tbody>
	</table>
</p>

<%= link_to "Add a course", home_add_course_path %>
<br />
<%= link_to "Remove a course", home_remove_course_path %>
<br />
<!--<%= link_to "Remove all", :controller => "home", :action => "remove_courses"%>-->
<br />
<br />
<%= link_to 'Back', home_courses_path %>

railsapp/app/views/home/courses.mobile.erb
<% if user_signed_in? %>

	<ul>
		<li class="arrow">
			<%=link_to "My Assignments", course_assignment_path(course)%>
			<small class="counter">></small>
		</li>
		
	</ul>
	
<% end %>

railsapp/app/views/home/index.html.erb
<!-- yes/no dialog -->
<% if current_user == nil && @show_dialog %>
	<script>
		$(document).ready(function(){
			setTimeout(function(){
				$("div.help a.modalInput").trigger('click');
			}, 100);
		});
	</script>
<% end %>
<% if current_user != nil && !current_user.has_seen_home %>
	<script>
	$(document).ready(function(){
		setTimeout(function(){
			$("div.help a.modalInput").trigger('click');
		}, 100);
	});
	</script>
	<% current_user.has_seen_home = true %>
	<% current_user.save %>
<% end %>

<div class="modal" id="yesno">
  <img style="margin-top: 10px; z-index: 10000;" src="/migrade_logo2.png" height="50px">
  <h2><br/>a better way of doing work.</h2>

  <p>
  	<b>Help</b> is just a stone's throw away with <i>Page Help</i> at the top right.
  	<br/>
  	<br/>
    Course announcements will be here.
    <br/>
    <br/>
    Always watch the links at the top of the page, they can help you navigrate migrade.
    <ul>
	    <% if current_user == nil %>
	    	<li><b>Login</b></li>
	    	<li><b>Register</b></li>
	    <% elsif current_user.role == "teacher" %>
	    	<li><b>Home</b> - Your news feed.</li>
	    	<li><b>Courses</b> - Your classes.</li>
	    	<li><b>Grades</b> - How you're students are doing.</li>
	    <% else %>
	    	<li><b>Home</b> - Your news feed.</li>
	    	<li><b>My Courses</b> - Your courses.</li>
	    	<li><b>My Grades</b> - How you're doing... good luck!</li>
	    <% end %>
    </ul>
  </p>

  <p>
    <button class="close"> Ok </button><span class="note"> You can also hit escape to close this dialog. </span>
  </p>
</div>

<h1>News</h1>

<% @mycourses.each do |course| %>
	<% if course.announcements.length > 0 %>
		<p>
			<h3><%=course.course_name%> - <%= course.course_description %></h3>
			
			<% course.announcements.each do |announcement| %>
				
				<div class = "announcement">
					<span class="date"><%= announcement.updated_at.strftime("%A, %b %d - %I:%M %p") %></span> - <%= course.professor.username %>

					<div>
						<b><%=announcement.title%></b>
						<br/>
						<%=announcement.text%>
					</div>
				</div>
				
			<%end%>
			
		</p>
	<% end %>
<%end%>

railsapp/app/views/home/index.mobile.erb
<% if user_signed_in? %>

	<ul>
		<li class="arrow">
			<%=link_to "My Courses", courses_path%>
			<small class="counter">></small>
		</li>
	</ul>

<% end %>

railsapp/app/views/home/remove_course.html.erb
<h1>My courses</h1>
<%= render :file => '/home/remove_course_form' %>
<br />
<br />
<br />
<%= link_to 'Back', home_courses_path %>

railsapp/app/views/home/remove_course.mobile.erb
<h1>My courses</h1>
<%= render :file => '/home/remove_course_form' %>
<br />
<br />
<br />
<%= link_to 'Back', home_path %>

railsapp/app/views/home/remove_course_form.html.erb
<%= form_tag() do |f|%>
	
	<table>
		
		<tr>
			<th>Course</th>
			<th>Remove?</th>
		</tr>
		
		<% for course in current_user.courses do %>
			<tr>
				<td><%= course.course_name %></td>
				<td><%= check_box_tag "courses[]", course.id %></td>
			</tr>
		<% end %>
	</table>
	<br />
	
	<%= submit_tag "Remove checked courses"%>
<%end%>

railsapp/app/views/home/remove_course_form.mobile.erb
<%= form_tag() do |f|%>
	
	<table>
		
		<tr>
			<th>Course</th>
			<th>Remove?</th>
		</tr>
		
		<% for course in current_user.courses do %>
			<tr>
				<td><%= course.course_name %></td>
				<td><%= check_box_tag "courses[]", course.id %></td>
			</tr>
		<% end %>
	</table>
	<br />
	
	<%= submit_tag "Remove checked courses"%>
<%end%>