railsapp/config/routes.rb
Webapp::Application.routes.draw do
  get "home/add_course"
  get "home/courses"
  match "/home/remove_course" => "home#remove_course"
  resources :home
  
  resources :courses do 
    resources :assignments
    resources :announcements
  end
    
  resources :grades
  
  devise_for :users
    
   
  
  

  root :to => 'home#index'

end

railsapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<% app_name = "migrade" %>
	<head>
	  <title><%= app_name %></title>

	  <%= stylesheet_link_tag    'application' %>
	  <%= stylesheet_link_tag	 'mobile' if mobile_device? %>
	  <%= javascript_include_tag 'application' %>
	  
	  <%= csrf_meta_tags %>
	
		<script src="http://cdn.jquerytools.org/1.2.6/full/jquery.tools.min.js"></script>
		<style>
		    .modal {
		    background-color:#fff;
		    display:none;
		    width:350px;
		    padding:15px;
		    text-align:left;
		    border:2px solid #333;
		
		    opacity:0.8;
		    -moz-border-radius:6px;
		    -webkit-border-radius:6px;
		    -moz-box-shadow: 0 0 50px #ccc;
		    -webkit-box-shadow: 0 0 50px #ccc;
		  }
		
		  .modal h2 {
		    background:url(/media/img/global/info.png) 0 50% no-repeat;
		    margin:0px;
		    padding:10px 0 10px 45px;
		    border-bottom:1px solid #333;
		    font-size:20px;
		  }
		</style>
	
	</head>
	
	<div id="header">
		<img style="margin-top: 10px;" src="/migrade_logo.png" height="30px">
		<div class = "help"><a class="modalInput" rel="#yesno"><span>Page help</span></a></div>
	</div>
	
	<div id=top-menu>
		<div id=account>
			<% if user_signed_in? %>
				Signed in as <%= link_to current_user.username, edit_user_registration_path %>
		  		<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
		  	<% else %>
		  		<%= link_to "Login", new_user_session_path %>
		  		<%= link_to "Register", new_user_registration_path %>
		  	<% end %>
		</div>
		
		<% if user_signed_in? %>
			<%= link_to "Home", home_index_path%>
			<% if current_user.role? "student"%>
				<%= link_to "My Courses", home_courses_path%>
				<%= link_to "All Courses", courses_path%>
				<%= link_to "My Grades", grades_path%>
			<%end%>
			<% if current_user.role? "teacher"%>
				<%= link_to "Courses", courses_path, :method => :get %>
				<%= link_to "Grades", grades_path, %>
			<%end%>
	  	<%end%>
	</div>
	
	
	  
	<body>
		<div class=nosidebar id=main>
			<div id=content>
				
				<%= yield %>
			</div>
		</div>
	</body>
	
	<div id=footer>
		
		<% if mobile_device? %>
				
			<%= link_to "Full Site", :mobile => 0 %>
			
		<% else %>
		
			<%= link_to "Mobile Site", :mobile => 1 %>
			
		<% end %>
		
	</div>
</html>

railsapp/app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<% app_name = "migrade" %>
	<head>
	  <title><%= app_name %></title>
	  <%= stylesheet_link_tag "mobile" %>
	  <%= javascript_include_tag "/jqtouch/jquery-1.7.min.js", "/jqtouch/jqtouch.min.js", "mobile" %>
	  <%= csrf_meta_tag %>
	  <%= javascript_include_tag "jquery.min", "jquery_ujs" %>
	  <meta name="viewport" content="width=device-width">
	  
	</head>
	
	<div id=top-menu>
		
		<div id=top-menu-left>
			<% if user_signed_in? %>			
		  		<%= link_to "Sign out", destroy_user_session_path, :method => :delete%>
			<% else %>
				<%= link_to "Login", new_user_session_path %>
			<% end %>
		</div>
		
		<div id=top-menu-right>
			<% if user_signed_in? %>			
				<%= link_to "Home", home_index_path%>
			<% else %>
		  		<%= link_to "Register", new_user_registration_path %>
			<% end %>
		</div>
	</div>
	
	<body>
	
	<div class="nosidebar" id="main">
		
		<div id="sidebar">
			
		</div>
		
		<div id="content">
			
			<%= yield %>
		</div>
		
	</div>
	
	</body>
	<div id=footer>
		
		<% if mobile_device? %>
				
			<%= link_to "Full Site", :mobile => 0 %>
			
		<% else %>
		
			<%= link_to "Mobile Site", :mobile => 1 %>
			
		<% end %>
		
	</div>
	
</html>