railsapp/config/routes.rb
Webapp::Application.routes.draw do
  get "home/add_course"
  get "home/courses"
  match "/home/remove_course" => "home#remove_course"
  resources :home
  
  resources :courses do 
    resources :assignments
    resources :announcements
  end
    
  resources :grades
  
  devise_for :users
    
   
  
  

  root :to => 'home#index'

end

railsapp/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.mobile
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new
    
    @course.users = [current_user]
    
    @course.save

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

end

railsapp/app/helpers/courses_helper.rb
module CoursesHelper
end

railsapp/app/views/courses/_form.html.erb
<%= form_for (@course) do |f| %>
  <div class="field">
    <%= f.label :course_name %><br />
    <%= f.text_field :course_name %>
  </div>
  <div class="field">
    <%= f.label :course_description %><br />
    <%= f.text_area :course_description, :rows => 3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsapp/app/views/courses/_form.mobile.erb
<%= form_for (@course) do |f| %>
  <div class="field">
    <%= f.label :course_name %><br />
    <%= f.text_field :course_name %>
  </div>
  <div class="field">
    <%= f.label :course_description %><br />
    <%= f.text_area :course_description, :rows => 3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsapp/app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', course_path(@course) %>

railsapp/app/views/courses/edit.mobile.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', course_path(@course) %>

railsapp/app/views/courses/index.html.erb
<h1>Listing courses</h1>
<br/>
<table class = "list">
  <thead>
	  <tr>
	    <th>Course name</th>
	    <th>Course description</th>
	    <th></th>
	    <th></th>
	  </tr>
  </thead>

    <tbody>
		<% @courses.each do |course| %>
		  <tr>
		    <td class = "middle"><%= link_to course.course_name, course_path(course) %></td>
		    <td class = "middle"><%= course.course_description %></td>
		    <td class = "last"><% if can? :update, course %><% if course.professor == current_user %><%= link_to 'Edit', edit_course_path(course) %><%end%><%end%></td>
		    <td class = "last"><% if can? :destroy, course %><% if course.professor == current_user %><%= link_to 'Destroy', course, confirm: 'Are you sure?', method: :delete %><%end%><%end%></td>
		  </tr>
		<% end %>
	</tbody>
</table>

<br />

<% if can? :create, Course %>
	<%= link_to 'New Course', new_course_path %>
<%end%>

railsapp/app/views/courses/index.mobile.erb
<% @mycourses = current_user.courses %>
<% if user_signed_in? %>

	<ul>
		<% for course in @mycourses %>
		
			<li class="arrow">
				<%=link_to h(course.course_name), course %>
				<small class="counter">></small>
			</li>
		<% end %>
		
	</ul>
	
	<br />

<% end %>

railsapp/app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

railsapp/app/views/courses/new.mobile.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

railsapp/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>
<% @assignments = @course.assignments%>	
<% @announcements = @course.announcements%>

<h2>Information:</h2>
<div class="announcement"><b>Course name: </b><%= @course.course_name %></div>
<div class="announcement"><b>Professor: </b><%= @course.professor.username %></div>
<div class="announcement"><b>Course description: </b><%= @course.course_description %></div>
<% if not current_user.role?("teacher") %>
	<div class="announcement"><b>Overall grade: </b><%= @course.grade(current_user) %>% / <%= @course.max_grade(current_user) %>%</div>
<% end %>
<br/>

<h2>Announcements
	<% if can? :create, Announcement %>
		<% if @course.professor == current_user %>
			-- <%=link_to "Add an announcement", new_course_announcement_path(@course)%>
		<% end %>
	<%end%>
</h2>

<% @announcements.each do |announcement| %>
	<div class="announcement"><%= announcement.updated_at.strftime("%A, %b %d - %I:%M %p") %> - <%= link_to announcement.title, course_announcement_path(@course, announcement)%></div>
<% end %>
<br/>

<h2>Assignments
	<% if can? :create, Assignment%>
		<% if @course.professor == current_user %>
			 -- <%= link_to "Add an assignment", new_course_assignment_path(@course, :type => 'new' )%>
		<% end %>
	<% end %>
</h2>


<% @assignments.each do |assignment| %>
	<div class="announcement">
		<% if @course.professor != current_user and assignment.submitted?(current_user) %>
			 	<img src="/checkmark.png" height="15px">
		<% end %>
		<% if @course.professor == current_user and @course.students.find_all { |u| assignment.submitted?(u) }.length > 0 and @course.students.find_all { |u| assignment.submitted?(u) }.all? { |u| assignment.graded?(u) } %>
			 	<img src="/checkmark.png" height="15px">
		<% end %>
		<%= link_to assignment.title, course_assignment_path(@course, assignment)%>
		<% if not assignment.submitted?(current_user) %>
		<% end %>
		<% if assignment.graded?(current_user) %>
			 	 <span class="note">- <%= assignment.grade(current_user) %>%</span>
		<% end %>
	</div>
<% end %>
<img src="/checkmark.png" height="10px"><span class="note"> - indicates you have <%= @course.professor == current_user ? "graded all submitted assignments" : "completed the assignment" %> </span>	


<br />
<br/>
<% if can? :update, Course%>
	<% if @course.professor == current_user %>
		<%= link_to 'Edit Course', edit_course_path(@course) %> |
	<%end%>
<%end%>
<%= link_to 'Back', courses_path %>

railsapp/app/views/courses/show.mobile.erb
<% @assignments = @course.assignments%>	
<% @announcements = @course.announcements%>


<h2>Information:</h2>
<div class="announcement"><b>Course name: </b><%= @course.course_name %></div>
<div class="announcement"><b>Professor: </b><%= @course.professor.username %></div>
<div class="announcement"><b>Course description: </b><%= @course.course_description %></div>
<% if not current_user.role?("teacher") %>
	<div class="announcement"><b>Overall grade: </b><%= @course.grade(current_user) %>% / <%= @course.max_grade(current_user) %>%</div>
<% end %>
<br/>


<% if user_signed_in? %>

	<h1>Assignments</h1>

	<% for assignment in @assignments %>
		<ul>
			<li class="arrow">
				<%=link_to h(assignment.title), course_assignment_path(@course, assignment)%>
				<small class="counter">></small>
			</li>
			
		</ul>
	<% end %>
	
	<h1>Announcements</h1>
	
		<% for announcement in @announcements %>
		<ul>
			<li class="arrow">
				<%= announcement.updated_at.strftime("%A, %b %d - %I:%M %p") %>
				 - 
				<%= link_to announcement.title, course_announcement_path(@course, announcement)%>				<small class="counter">></small>
			</li>
			
		</ul>
	<% end %>
<% end %>